# Generated by Django 5.0.6 on 2026-05-13 17:22

import django.contrib.postgres.fields
import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.user')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='accounts.user')),
                ('project', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='projects.project')),
            ],
            options={
                'db_table': 'Paper',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('marks', models.IntegerField(default=1)),
                ('bloom_taxonomy', models.CharField(blank=True, db_column='bloomTaxonomy', max_length=50, null=True)),
                ('paper', models.ForeignKey(blank=True, db_column='paperId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.paper')),
                ('project', models.ForeignKey(blank=True, db_column='projectId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.project')),
            ],
            options={
                'db_table': 'Question',
            },
        ),
    ]
