# Generated by Django 5.0.6 on 2026-05-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='grade_class',
            field=models.CharField(blank=True, db_column='gradeClass', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='inferred_chapter',
            field=models.CharField(blank=True, db_column='inferredChapter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='inferred_topic',
            field=models.CharField(blank=True, db_column='inferredTopic', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source_pdf',
            field=models.CharField(blank=True, db_column='sourcePdf', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
