# Generated by Django 5.0.6 on 2026-07-20 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_account_user_remove_session_user_and_more"),
        ("projects", "0005_paper_s3_content_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="content_hash",
            field=models.CharField(
                blank=True, db_column="contentHash", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="image_url",
            field=models.CharField(
                blank=True, db_column="imageUrl", max_length=2048, null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="question",
            name="pool_id",
            field=models.CharField(
                blank=True, db_column="poolId", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_type",
            field=models.CharField(
                blank=True, db_column="sourceType", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="userId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="accounts.user",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["user", "subject", "grade_class"],
                name="question_user_subj_class_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["user", "content_hash"], name="question_user_hash_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["pool_id"], name="question_pool_idx"),
        ),
    ]
