# Generated by Django 5.0.6 on 2026-07-22 08:08

import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_backfill_question_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="blueprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="board",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="grade_class",
            field=models.CharField(
                blank=True, db_column="gradeClass", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="question_pool_id",
            field=models.CharField(
                blank=True, db_column="questionPoolId", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="PaperSet",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "id",
                    models.CharField(
                        default=utils.ids.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=1)),
                ("content", models.TextField()),
                ("answers", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "s3_pdf_key",
                    models.CharField(
                        blank=True, db_column="s3PdfKey", max_length=1024, null=True
                    ),
                ),
                (
                    "s3_docx_key",
                    models.CharField(
                        blank=True, db_column="s3DocxKey", max_length=1024, null=True
                    ),
                ),
                (
                    "s3_content_key",
                    models.CharField(
                        blank=True, db_column="s3ContentKey", max_length=1024, null=True
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        db_column="paperId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="projects.paper",
                    ),
                ),
            ],
            options={
                "db_table": "PaperSet",
                "ordering": ["order"],
            },
        ),
    ]
