# Generated by Django 5.0.6 on 2026-07-22 08:08

from django.db import migrations
import uuid

def generate_id():
    return uuid.uuid4().hex

def migrate_papers_to_sets(apps, schema_editor):
    Paper = apps.get_model('projects', 'Paper')
    PaperSet = apps.get_model('projects', 'PaperSet')
    
    for paper in Paper.objects.all():
        PaperSet.objects.create(
            id=generate_id(),
            paper=paper,
            label="Set A",
            order=1,
            content=paper.content,
            s3_pdf_key=paper.s3_pdf_key,
            s3_docx_key=paper.s3_docx_key,
            s3_content_key=paper.s3_content_key,
        )
        
        # Try to infer class/subject from project name (e.g. "Class 10 - Science - Light")
        if paper.project and paper.project.name:
            parts = [p.strip() for p in paper.project.name.replace("—", "-").replace("–", "-").split("-")]
            if len(parts) >= 1:
                paper.grade_class = parts[0]
            if len(parts) >= 2:
                paper.subject = parts[1]
            paper.save()

def reverse_migrate_papers_to_sets(apps, schema_editor):
    Paper = apps.get_model('projects', 'Paper')
    for paper in Paper.objects.all():
        first_set = paper.sets.order_by('order').first()
        if first_set:
            paper.content = first_set.content
            paper.s3_pdf_key = first_set.s3_pdf_key
            paper.s3_docx_key = first_set.s3_docx_key
            paper.s3_content_key = first_set.s3_content_key
            paper.save()

class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_add_paper_sets"),
    ]

    operations = [
        migrations.RunPython(migrate_papers_to_sets, reverse_migrate_papers_to_sets)
    ]
