# Generated by Django 5.0.6 on 2026-07-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_convert_paper_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="content",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="s3_content_key",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="s3_docx_key",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="s3_pdf_key",
        ),
    ]
