# Generated by Django 5.0.6 on 2026-07-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_legacy_paper_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionFamily",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("response_mode", models.CharField(max_length=50)),
                ("is_auto_markable", models.BooleanField()),
                ("sort_order", models.IntegerField()),
            ],
            options={
                "db_table": "QuestionFamily",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("purpose", models.TextField(blank=True, null=True)),
                ("is_container", models.BooleanField(default=False)),
                ("requires_stimulus", models.BooleanField(default=False)),
                ("requires_options", models.BooleanField(default=False)),
                ("requires_figure", models.BooleanField(default=False)),
                ("produces_figure", models.BooleanField(default=False)),
                ("is_auto_markable", models.BooleanField(default=False)),
                ("is_competency_default", models.BooleanField(default=False)),
                ("needs_answer_space", models.BooleanField(default=True)),
                (
                    "default_answer_space_lines",
                    models.IntegerField(blank=True, null=True),
                ),
                ("is_internal_only", models.BooleanField(default=False)),
                ("content_schema", models.JSONField(blank=True, default=dict)),
                ("answer_schema", models.JSONField(blank=True, default=dict)),
                ("deprecated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="types",
                        to="projects.questionfamily",
                    ),
                ),
            ],
            options={
                "db_table": "QuestionType",
            },
        ),
        migrations.CreateModel(
            name="QuestionTypeAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=255)),
                ("locale", models.CharField(blank=True, max_length=10, null=True)),
                ("board_code", models.CharField(blank=True, max_length=50, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="projects.questiontype",
                    ),
                ),
            ],
            options={
                "db_table": "QuestionTypeAlias",
                "indexes": [
                    models.Index(fields=["alias"], name="question_type_alias_idx")
                ],
                "unique_together": {("type", "alias", "locale", "board_code")},
            },
        ),
    ]
