# Generated by Django 5.0.6 on 2026-07-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_seed_question_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_column="type",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.questiontype",
            ),
        ),
    ]
