# Generated by Django 5.0.6 on 2026-08-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_merge_20260805_1136"),
        ("projects", "0013_alter_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_column="deletedAt", null=True),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["user", "deleted_at", "-updated_at"],
                name="paper_user_deleted_idx",
            ),
        ),
    ]
