# Generated by Django 5.0.6 on 2026-08-20 05:16

import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_merge_20260805_1136"),
        ("projects", "0014_paper_deleted_at_paper_paper_user_deleted_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "id",
                    models.CharField(
                        default=utils.ids.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope", models.CharField(max_length=64)),
                ("set_label", models.CharField(blank=True, default="", max_length=8)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "class_name",
                    models.CharField(
                        blank=True, db_column="className", default="", max_length=100
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("document", models.JSONField(blank=True, default=dict)),
                (
                    "client_updated_at",
                    models.BigIntegerField(db_column="clientUpdatedAt", default=0),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "Draft",
                "ordering": ["-client_updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-client_updated_at"],
                        name="draft_user_recent_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="draft",
            constraint=models.UniqueConstraint(
                fields=("user", "scope", "set_label"),
                name="unique_draft_per_scope_and_set",
            ),
        ),
    ]
