import os

with open("scripts/seed_data.py", "r") as f:
    seed_data = f.read()

migration_content = f"""# Generated by Django 5.0.6 on 2026-07-23

from django.db import migrations

{seed_data}

def seed_data(apps, schema_editor):
    QuestionFamily = apps.get_model('projects', 'QuestionFamily')
    QuestionType = apps.get_model('projects', 'QuestionType')
    Question = apps.get_model('projects', 'Question')
    
    for fam in FAMILIES:
        QuestionFamily.objects.update_or_create(code=fam['code'], defaults=fam)
        
    for type_data in TYPES:
        fam = QuestionFamily.objects.get(code=type_data.pop('family'))
        type_data['family'] = fam
        QuestionType.objects.update_or_create(code=type_data['code'], defaults=type_data)

    # Basic data migration mapping for old string types to new canonical codes
    mapping = {{
        'LONG_ANSWER': 'LA',
        'HOTS': 'SA',
        'CASE_STUDY': 'CASE_STUDY',
        'COMPETENCY': 'SA',
        'VERY_SHORT_ANSWER': 'VSA',
        'SHORT_ANSWER': 'SA',
        'MCQ': 'MCQ_SINGLE',
        'ASSERTION_REASON': 'ASSERTION_REASON',
        'DIAGRAM': 'DIAGRAM_DRAW',
        'NUMERICAL': 'NUMERICAL',
    }}
    
    for old, new in mapping.items():
        Question.objects.filter(type=old).update(type=new)

def reverse_seed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_questionfamily_questiontype_questiontypealias"),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed),
    ]
"""

with open("apps/projects/migrations/0012_seed_question_types.py", "w") as f:
    f.write(migration_content)
