"use client";

import { useEffect, useState, useMemo } from "react";
import { fetchJson } from "@/lib/api-client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Search, History, Calendar, FileText, ChevronDown, ChevronUp, Copy, Check } from "lucide-react";
import { useEditorStore } from "@/store/editor-store";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

type HistoryItem = {
  id: string;
  prompt: string;
  settings: {
    topic: string;
    count: number;
    difficulty: string;
    documentIds: string[];
    instructions?: string;
  };
  result: {
    sections?: Array<{
      title: string;
      questions: Array<{
        content: string;
        type: string;
        options?: string[];
        answer?: string;
        marks: number;
      }>;
    }>;
    questions?: Array<{
      content: string;
      type: string;
      options?: string[];
      answer?: string;
      marks: number;
    }>;
  };
  created_at: string;
};

const formatDate = (value?: string) => {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

export default function HistoryPage() {
  const [historyItems, setHistoryItems] = useState<HistoryItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());

  useEffect(() => {
    fetchJson<HistoryItem[]>("/api/generation/history")
      .then(setHistoryItems)
      .catch((err) => {
        console.error(err);
        toast.error("Failed to load generation history.");
      })
      .finally(() => setIsLoading(false));
  }, []);

  const toggleExpand = (id: string) => {
    setExpandedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const handleInsertIntoEditor = (item: HistoryItem) => {
    const { result } = item;
    if (!result) {
      toast.error("No questions found in this generation.");
      return;
    }

    const hasSections = result.sections && result.sections.length > 0;

    if (hasSections) {
      const sections = result.sections!.map((section) => ({
        title: section.title,
        questions: section.questions.map((q) => ({
          content: q.content,
          type: q.type,
          options: q.options || [],
          answer: q.answer || "",
          marks: q.marks,
        })),
      }));
      useEditorStore.getState().appendSections(sections);
      toast.success("Inserted generated sections into the editor.");
    } else if (result.questions && result.questions.length > 0) {
      const allQuestions = result.questions.map((q) => ({
        content: q.content,
        type: q.type,
        options: q.options || [],
        answer: q.answer || "",
        marks: q.marks,
      }));
      useEditorStore.getState().appendQuestions(allQuestions);
      toast.success("Inserted generated questions into the editor.");
    } else {
      toast.error("No valid questions or sections found to insert.");
    }
  };

  const filteredHistory = useMemo(() => {
    const term = searchQuery.trim().toLowerCase();
    if (!term) return historyItems;
    return historyItems.filter((item) => {
      const topic = item.settings.topic.toLowerCase();
      const prompt = item.prompt.toLowerCase();
      const difficulty = item.settings.difficulty.toLowerCase();
      return topic.includes(term) || prompt.includes(term) || difficulty.includes(term);
    });
  }, [historyItems, searchQuery]);

  return (
    <div className="p-8 max-w-5xl mx-auto space-y-8 bg-background min-h-full">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold tracking-tight text-foreground flex items-center gap-2.5">
            <History className="h-7 w-7 text-indigo-500" />
            Generation History
          </h2>
          <p className="text-muted-foreground mt-2">
            Browse and manage all exam question sets generated by AI so far.
          </p>
        </div>
        <div className="w-full md:w-80 relative">
          <Search className="absolute left-3 top-2.5 h-4.5 w-4.5 text-muted-foreground" />
          <Input
            placeholder="Search generations..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-9 bg-background border-border text-foreground"
          />
        </div>
      </div>

      {isLoading ? (
        <div className="text-center py-20 border border-dashed border-border rounded-xl bg-card">
          <p className="text-muted-foreground text-sm">Loading generation history...</p>
        </div>
      ) : filteredHistory.length === 0 ? (
        <div className="text-center py-20 border border-dashed border-border rounded-xl bg-card">
          <p className="text-muted-foreground text-sm">
            {searchQuery ? "No history matches your search filter." : "No generation history found."}
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {filteredHistory.map((item) => {
            const isExpanded = expandedIds.has(item.id);
            const questionCount = item.settings.count;
            
            return (
              <Card key={item.id} className="bg-card border-border hover:shadow-sm transition-all duration-200">
                {/* Header */}
                <div
                  role="button"
                  tabIndex={0}
                  onClick={() => toggleExpand(item.id)}
                  onKeyDown={(e) => e.key === "Enter" && toggleExpand(item.id)}
                  className="p-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 cursor-pointer select-none"
                >
                  <div className="space-y-2">
                    <div className="flex flex-wrap items-center gap-2">
                      <h3 className="text-lg font-bold text-foreground tracking-tight">
                        {item.settings.topic}
                      </h3>
                      <Badge variant="outline" className="text-[10px] font-semibold uppercase tracking-wider text-indigo-500 border-indigo-500/35 bg-indigo-500/5">
                        {item.settings.difficulty}
                      </Badge>
                      <Badge variant="secondary" className="text-[10px] font-bold">
                        {questionCount} Questions
                      </Badge>
                    </div>
                    <div className="flex items-center gap-4 text-xs text-muted-foreground">
                      <span className="flex items-center gap-1">
                        <Calendar className="h-3.5 w-3.5" />
                        {formatDate(item.created_at)}
                      </span>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 self-stretch md:self-auto justify-end">
                    <Button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleInsertIntoEditor(item);
                      }}
                      className="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-xs py-1.5 h-8 gap-1.5"
                    >
                      <FileText className="h-3.5 w-3.5" />
                      Insert into Editor
                    </Button>
                    <div className="text-muted-foreground p-1.5 hover:bg-accent rounded-lg transition-colors">
                      {isExpanded ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
                    </div>
                  </div>
                </div>

                {/* Expanded content */}
                {isExpanded && (
                  <CardContent className="border-t border-border pt-6 pb-6 bg-muted/5 space-y-6">
                    {/* Raw prompt / info */}
                    {item.settings.instructions && (
                      <div className="space-y-1.5">
                        <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider block">
                          AI Directives
                        </span>
                        <div className="text-xs bg-muted/40 p-3 rounded-lg border border-border text-foreground max-h-24 overflow-y-auto whitespace-pre-wrap">
                          {item.settings.instructions}
                        </div>
                      </div>
                    )}

                    {/* Render generated output preview */}
                    <div className="space-y-4">
                      <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider block">
                        Generated Questions Preview
                      </span>

                      <div className="space-y-4">
                        {/* Sections layout */}
                        {item.result.sections && item.result.sections.length > 0 ? (
                          item.result.sections.map((section, sIdx) => (
                            <div key={sIdx} className="space-y-3">
                              <h4 className="text-xs font-bold text-indigo-500 uppercase tracking-wide">
                                {section.title}
                              </h4>
                              <div className="grid gap-3 md:grid-cols-2">
                                {section.questions.map((q, qIdx) => (
                                  <div key={qIdx} className="p-4 bg-background border border-border rounded-xl space-y-2">
                                    <div className="flex justify-between items-start gap-2">
                                      <p className="font-semibold text-sm text-foreground">
                                        {q.content}
                                      </p>
                                      <Badge variant="secondary" className="text-[10px] font-bold flex-shrink-0">
                                        {q.marks} Marks
                                      </Badge>
                                    </div>
                                    {q.options && q.options.length > 0 && (
                                      <div className="grid grid-cols-2 gap-2 mt-2">
                                        {q.options.map((opt, oIdx) => (
                                          <div key={oIdx} className="text-[10px] text-muted-foreground p-1.5 border border-border rounded bg-muted/10 truncate">
                                            {String.fromCharCode(65 + oIdx)}. {opt}
                                          </div>
                                        ))}
                                      </div>
                                    )}
                                    {q.answer && (
                                      <div className="mt-2 pt-2 border-t border-border text-[10px] text-green-600 dark:text-green-500 font-semibold truncate">
                                        Ans: {q.answer}
                                      </div>
                                    )}
                                  </div>
                                ))}
                              </div>
                            </div>
                          ))
                        ) : item.result.questions && item.result.questions.length > 0 ? (
                          <div className="grid gap-3 md:grid-cols-2">
                            {item.result.questions.map((q, qIdx) => (
                              <div key={qIdx} className="p-4 bg-background border border-border rounded-xl space-y-2">
                                <div className="flex justify-between items-start gap-2">
                                  <p className="font-semibold text-sm text-foreground">
                                    {q.content}
                                  </p>
                                  <Badge variant="secondary" className="text-[10px] font-bold flex-shrink-0">
                                    {q.marks} Marks
                                  </Badge>
                                </div>
                                {q.options && q.options.length > 0 && (
                                  <div className="grid grid-cols-2 gap-2 mt-2">
                                    {q.options.map((opt, oIdx) => (
                                      <div key={oIdx} className="text-[10px] text-muted-foreground p-1.5 border border-border rounded bg-muted/10 truncate">
                                        {String.fromCharCode(65 + oIdx)}. {opt}
                                      </div>
                                    ))}
                                  </div>
                                )}
                                {q.answer && (
                                  <div className="mt-2 pt-2 border-t border-border text-[10px] text-green-600 dark:text-green-500 font-semibold truncate">
                                    Ans: {q.answer}
                                  </div>
                                )}
                              </div>
                            ))}
                          </div>
                        ) : (
                          <p className="text-xs text-muted-foreground">No questions found in this generation result.</p>
                        )}
                      </div>
                    </div>
                  </CardContent>
                )}
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
