# Generated by Django 5.0.6 on 2026-05-13 17:22

import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('settings', models.JSONField()),
                ('result', models.JSONField()),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.user')),
            ],
            options={
                'db_table': 'GenerationHistory',
            },
        ),
    ]
