# Generated by GitHub Copilot on 2026-05-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE \"GenerationHistory\"
            ADD COLUMN IF NOT EXISTS \"createdAt\" timestamptz NOT NULL DEFAULT NOW();
            ALTER TABLE \"GenerationHistory\"
            ADD COLUMN IF NOT EXISTS \"updatedAt\" timestamptz NOT NULL DEFAULT NOW();
            """,
            reverse_sql="SELECT 1;",
        ),
    ]
