# Generated by Django 5.0.6 on 2026-07-28 09:58

import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_account_user_remove_session_user_and_more"),
        ("generation", "0003_add_api_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "id",
                    models.CharField(
                        default=utils.ids.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("instructions", models.TextField(blank=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, db_column="lastUsedAt", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_templates",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "PaperTemplate",
                "ordering": ["-last_used_at", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="papertemplate",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_template_name_per_user"
            ),
        ),
    ]
