# Generated by Django 5.0.6 on 2026-07-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0004_papertemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertemplate",
            name="base_template_id",
            field=models.CharField(
                blank=True, db_column="baseTemplateId", default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="blueprint",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="source_config",
            field=models.JSONField(blank=True, db_column="sourceConfig", default=dict),
        ),
    ]
