# Generated by Django 5.0.6 on 2026-08-03 10:58

import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_user_remove_session_user_and_more'),
        ('generation', '0005_papertemplate_base_template_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('paper_id', models.CharField(blank=True, db_column='paperId', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('phase', models.CharField(blank=True, max_length=200)),
                ('produced', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(db_column='cancelRequested', default=False)),
                ('heartbeat_at', models.DateTimeField(blank=True, db_column='heartbeatAt', null=True)),
                ('finished_at', models.DateTimeField(blank=True, db_column='finishedAt', null=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='accounts.user')),
            ],
            options={
                'db_table': 'GenerationRun',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRunEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('event', models.CharField(max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('run', models.ForeignKey(db_column='runId', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='generation.generationrun')),
            ],
            options={
                'db_table': 'GenerationRunEvent',
                'ordering': ['seq'],
            },
        ),
        migrations.AddIndex(
            model_name='generationrun',
            index=models.Index(fields=['user', 'status'], name='GenerationR_userId_977fce_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrun',
            index=models.Index(fields=['status', 'heartbeat_at'], name='GenerationR_status_f0ad55_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrunevent',
            index=models.Index(fields=['run', 'seq'], name='GenerationR_runId_0f0756_idx'),
        ),
        migrations.AddConstraint(
            model_name='generationrunevent',
            constraint=models.UniqueConstraint(fields=('run', 'seq'), name='generation_run_event_unique_seq'),
        ),
    ]
