# Generated by Django 5.0.6 on 2026-08-03 10:39

import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_account_user_remove_session_user_and_more"),
        ("generation", "0005_papertemplate_base_template_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateFolder",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "id",
                    models.CharField(
                        default=utils.ids.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parentId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="generation.templatefolder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_folders",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "TemplateFolder",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                db_column="folderId",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="generation.templatefolder",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatefolder",
            constraint=models.UniqueConstraint(
                fields=("user", "parent", "name"),
                name="unique_subfolder_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatefolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("user", "name"),
                name="unique_root_folder_name_per_user",
            ),
        ),
    ]
