# Generated by Django 5.0.6 on 2026-08-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0006_apiusage_organization'),
        ('generation', '0006_templatefolder_papertemplate_folder_and_more'),
    ]

    operations = [
    ]
