# Generated by Django 5.0.6 on 2026-08-20 05:31

import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_active_organization"),
        ("generation", "0007_merge_20260805_1136"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "id",
                    models.CharField(
                        default=utils.ids.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("request", models.JSONField(blank=True, default=dict)),
                (
                    "heartbeat_at",
                    models.DateTimeField(auto_now_add=True, db_column="heartbeatAt"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, db_column="finishedAt", null=True),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_runs",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "GenerationRun",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=utils.ids.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.IntegerField()),
                ("name", models.CharField(blank=True, default="", max_length=64)),
                ("frame", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="generation.generationrun",
                    ),
                ),
            ],
            options={
                "db_table": "GenerationEvent",
                "ordering": ["seq"],
            },
        ),
        migrations.AddIndex(
            model_name="generationrun",
            index=models.Index(
                fields=["user", "-created_at"], name="genrun_user_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationrun",
            index=models.Index(
                fields=["status", "heartbeat_at"], name="genrun_status_beat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationevent",
            index=models.Index(fields=["run", "seq"], name="genevent_run_seq_idx"),
        ),
        migrations.AddConstraint(
            model_name="generationevent",
            constraint=models.UniqueConstraint(
                fields=("run", "seq"), name="unique_event_seq_per_run"
            ),
        ),
    ]
