# Generated by Django 5.0.6 on 2026-05-13 17:22

import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(db_column='emailVerified', default=False)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(db_column='expiresAt')),
            ],
            options={
                'db_table': 'verification',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_column='expiresAt')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.CharField(blank=True, db_column='ipAddress', max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, db_column='userAgent', null=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.user')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('account_id', models.CharField(db_column='accountId', max_length=255)),
                ('provider_id', models.CharField(db_column='providerId', max_length=255)),
                ('access_token', models.TextField(blank=True, db_column='accessToken', null=True)),
                ('refresh_token', models.TextField(blank=True, db_column='refreshToken', null=True)),
                ('id_token', models.TextField(blank=True, db_column='idToken', null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, db_column='accessTokenExpiresAt', null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, db_column='refreshTokenExpiresAt', null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.user')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
