# Generated by Django 5.0.6 on 2026-08-03 11:04

import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_account_user_remove_session_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandKit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "id",
                    models.CharField(
                        default=utils.ids.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "institute_name",
                    models.CharField(
                        blank=True,
                        db_column="instituteName",
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "institute_address",
                    models.TextField(
                        blank=True, db_column="instituteAddress", default=""
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True, db_column="accentColor", default="", max_length=9
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        blank=True, db_column="fontFamily", default="", max_length=120
                    ),
                ),
                (
                    "header_layout",
                    models.JSONField(
                        blank=True, db_column="headerLayout", default=dict
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_kit",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "BrandKit",
            },
        ),
        migrations.CreateModel(
            name="BrandAsset",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "id",
                    models.CharField(
                        default=utils.ids.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("kind", models.CharField(default="logo", max_length=20)),
                (
                    "storage_path",
                    models.CharField(db_column="storagePath", max_length=500),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "kit",
                    models.ForeignKey(
                        db_column="kitId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="accounts.brandkit",
                    ),
                ),
            ],
            options={
                "db_table": "BrandAsset",
                "ordering": ["created_at"],
            },
        ),
    ]
