# Generated by Django 5.0.6 on 2026-08-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_brandkit_brandasset'),
        ('accounts', '0004_user_is_superadmin'),
    ]

    operations = [
    ]
