# Generated by Django 5.0.6 on 2026-08-20 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_merge_20260805_1136"),
        ("organizations", "0004_organization_email_domains_organizationinvite_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_users",
                to="organizations.organization",
            ),
        ),
    ]
