# Generated by Django 5.0.6 on 2026-05-13 17:22

import django.db.models.deletion
import pgvector.django
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(db_column='type', default='pdf', max_length=255)),
                ('project', models.ForeignKey(blank=True, db_column='projectId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.user')),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.CharField(default=utils.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('page', models.IntegerField(blank=True, null=True)),
                ('chunk_index', models.IntegerField(db_column='chunkIndex')),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('document', models.ForeignKey(db_column='documentId', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'db_table': 'DocumentChunk',
                'indexes': [models.Index(fields=['document'], name='document_chunk_document_idx')],
            },
        ),
    ]
