# Generated by Django 5.0.6 on 2026-08-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_sqlite_pdfsourceid_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfsource",
            name="detected_subject",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="pdfsource",
            name="subject_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
