# Generated by Django 5.0.6 on 2026-07-27 16:31

import django.db.models.deletion
import utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_remove_account_user_remove_session_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "id",
                    models.CharField(
                        default=utils.ids.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New chat", max_length=255)),
                ("spec", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "Conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "id",
                    models.CharField(
                        default=utils.ids.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                (
                    "conversation",
                    models.ForeignKey(
                        db_column="conversationId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "ChatMessage",
                "ordering": ["created_at"],
            },
        ),
    ]
