# Generated by Django 5.0.6 on 2026-07-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="mode",
            field=models.CharField(
                choices=[("chat", "Chat"), ("paper", "Paper session")],
                default="chat",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="paper_id",
            field=models.CharField(
                blank=True, db_column="paperId", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=16,
            ),
        ),
    ]
