"""Family F (i–ii) — language: grammar and vocabulary.

Grammar and vocabulary items test the rule, not the story, so they are
`lane="original"`: never built on a character, plot or poem from a syllabus.
Types an existing independent generator already writes carry a `route` to it.

Hindi and Telugu use the same structural types under local names (संधि,
समास, मुहावरे, पर्यायवाची, विलोम; సంధి, సమాసం, అలంకారం). Those are aliases on
these types, not new types.
"""

from __future__ import annotations

from services.question_types.catalog._build import FOUR, family_builder
from services.question_types.spec import Route

_ = family_builder("LANGUAGE")

_LANGUAGES = ("english", "hindi", "telugu", "sanskrit")
_GRAMMAR = Route("grammar_asset_pool", "grammar_task_set")

ENTRIES = [
    _("GRAMMAR_ITEM", "Grammar Item", "F1", "LIVE", "GRAMMAR",
      "A single grammar rule.", 1, (2, 10), "SHORT_TEXT", "APPLY",
      lane="original", route=_GRAMMAR, subjects=_LANGUAGES,
      aliases=("GRAMMAR", "GRAMMAR QUESTION", "व्याकरण", "వ్యాకరణం"),
      brief="One self-contained grammar task on one named rule, in an invented sentence.",
      example="Fill in the blank with the correct preposition.\nThe book is ________ the table.",
      answer="on", notes="Generic fallback — prefer a specific grammar type."),
    _("GAP_FILL_GRAMMAR", "Gap Fill — Grammar Passage", "F2", "NEW", "GRAMMAR",
      "Grammar in continuous text.", 6, (5, 10), "SHORT_TEXT", "APPLY",
      marks_range=(3, 12), stimulus="PASSAGE", container="SUB_PARTS", lane="original",
      route=_GRAMMAR, subjects=_LANGUAGES, aliases=("GAP FILLING", "GAP FILL", "CLOZE"),
      brief="An invented short passage with numbered gaps (i), (ii)…, each filled with the correct form of a word given in brackets. 1 mark per gap.",
      example="Last Sunday, we (i) ________ (go) to the zoo. It (ii) ________ (be) very crowded. While we (iii) ________ (watch) the lions, it began to rain.",
      answer="(i) went (ii) was (iii) were watching"),
    _("ERROR_CORRECTION", "Error Correction", "F3", "DB", "GRAMMAR",
      "Spotting and fixing an error.", 2, (5, 10), "SHORT_TEXT", "CORRECT",
      marks_range=(1, 4), container="SUB_PARTS", lane="original", route=_GRAMMAR,
      subjects=_LANGUAGES, aliases=("CORRECT THE ERROR", "ERROR SPOTTING"),
      brief="Sentences numbered (i), (ii)… each containing exactly ONE error; the answer gives the incorrect word and its correction for each. 1 mark each.",
      example="Correct the error in each sentence.\n(i) She don't like mangoes.\n(ii) He is going to school yesterday.",
      answer="(i) don't → doesn't (ii) is going → went"),
    _("EDITING_OMISSION", "Editing — Omission", "F4", "NEW", "GRAMMAR",
      "Identifying a missing word.", 2, (6, 10), "SHORT_TEXT", "CORRECT",
      marks_range=(1, 4), stimulus="PASSAGE", container="SUB_PARTS", lane="original",
      route=_GRAMMAR, subjects=_LANGUAGES, aliases=("OMISSION", "EDITING"),
      brief="Lines of an invented passage each missing one word; the answer gives the word before, the missing word and the word after, for each line.",
      example="One word is missing in each line. Write it with the words before and after it.\nThe boy was walking the road.\nHe saw old man sitting there.",
      answer="walking / along / the · saw / an / old"),
    _("SENTENCE_TRANSFORM", "Sentence Transformation", "F5", "DB", "GRAMMAR",
      "Structural manipulation without changing meaning.", 1, (5, 10), "SHORT_TEXT", "APPLY",
      marks_range=(1, 2), lane="original", route=_GRAMMAR, subjects=_LANGUAGES,
      aliases=("REWRITE AS DIRECTED", "DO AS DIRECTED", "TRANSFORMATION OF SENTENCES"),
      brief="A sentence plus the direction in brackets, e.g. '(Rewrite using so…that)'. The direction is part of the item.",
      example="Rewrite as directed.\nHe is too weak to walk. (Rewrite using 'so…that')",
      answer="He is so weak that he cannot walk."),
    _("REARRANGE_WORDS", "Rearrange the Words", "F6", "DB", "GRAMMAR",
      "Syntax and word order.", 1, (2, 10), "ORDER", "SEQUENCE",
      lane="original", subjects=_LANGUAGES, aliases=("JUMBLED WORDS", "REARRANGE", "JUMBLED SENTENCE"),
      brief="The words of one sentence separated by slashes in shuffled order; the student writes the meaningful sentence.",
      example="Rearrange the words to form a meaningful sentence.\ngarden / the / are / roses / in / blooming",
      answer="Roses are blooming in the garden."),
    _("REPORTED_SPEECH", "Reported Speech", "F7", "NEW", "GRAMMAR",
      "Direct to indirect speech.", 1, (6, 10), "SHORT_TEXT", "APPLY",
      lane="original", route=_GRAMMAR, subjects=_LANGUAGES,
      aliases=("INDIRECT SPEECH", "NARRATION", "DIRECT AND INDIRECT SPEECH"),
      brief="One sentence in direct speech; the student reports it.",
      example="Report the following.\nRavi said to Sita, \"I am going to the market.\"",
      answer="Ravi told Sita that he was going to the market."),
    _("ACTIVE_PASSIVE", "Active / Passive Voice", "F8", "NEW", "GRAMMAR",
      "Voice change.", 1, (6, 10), "SHORT_TEXT", "APPLY",
      lane="original", route=_GRAMMAR, subjects=_LANGUAGES, aliases=("VOICE", "CHANGE THE VOICE", "PASSIVE VOICE"),
      brief="One sentence and the direction 'Change into passive voice' (or active).",
      example="Change into passive voice.\nThe gardener waters the plants every morning.",
      answer="The plants are watered by the gardener every morning."),
    _("CONNECTOR_CLAUSE", "Connectors / Clause Joining", "F9", "NEW", "GRAMMAR",
      "Joining sentences with a suitable connector.", 1, (5, 10), "SHORT_TEXT", "APPLY",
      lane="original", subjects=_LANGUAGES, aliases=("JOIN THE SENTENCES", "CONNECTORS"),
      brief="Two short sentences to be joined into one using a suitable connector.",
      example="Join the sentences using a suitable connector.\nIt was raining heavily. We went out for a walk.",
      answer="Although it was raining heavily, we went out for a walk."),
    _("PUNCTUATION", "Punctuation & Capitalisation", "F10", "NEW", "GRAMMAR",
      "Punctuation and capital letters.", 1, (1, 8), "SHORT_TEXT", "CORRECT",
      marks_range=(1, 2), lane="original", subjects=_LANGUAGES, aliases=("PUNCTUATE",),
      brief="One unpunctuated, uncapitalised sentence; the student rewrites it correctly.",
      example="Punctuate the sentence correctly.\nwhere are you going asked mother",
      answer="\"Where are you going?\" asked Mother."),
    _("VOCABULARY_ITEM", "Vocabulary Item", "F11", "DB", "GRAMMAR",
      "Word knowledge.", 1, (2, 10), "SHORT_TEXT", "RECALL",
      lane="original", subjects=_LANGUAGES, aliases=("VOCABULARY",),
      brief="One self-contained vocabulary task (word meaning, word use or word choice) in an invented sentence.",
      example="Use the word 'reluctant' in a sentence of your own.",
      answer="Any sentence using 'reluctant' correctly"),
    _("SYNONYM_ANTONYM", "Synonyms & Antonyms", "F12", "NEW", "ONE_WORD",
      "Word meaning relationships.", 1, (2, 10), "SHORT_TEXT", "RECALL",
      marking="KEYWORD_SET", lane="original", subjects=_LANGUAGES,
      aliases=("SYNONYMS", "ANTONYMS", "OPPOSITES", "पर्यायवाची शब्द", "विलोम शब्द"),
      brief="A word; the student writes its synonym or antonym as directed. The answer lists acceptable words.",
      example="Write the antonym of: generous",
      answer="selfish / stingy"),
    _("WORD_MEANING_CONTEXT", "Word Meaning in Context", "F13", "NEW", "ONE_WORD",
      "Meaning from context.", 1, (3, 10), "SHORT_TEXT", "INTERPRET",
      stimulus="PASSAGE", availability="internal", subjects=_LANGUAGES,
      reason="Asked as a part inside an unseen passage, not on its own."),
    _("IDIOM_PHRASE", "Idioms & Phrases", "F14", "NEW", "SHORT_ANSWER",
      "Figurative expressions.", 1, (5, 10), "SHORT_TEXT", "APPLY",
      marking="KEYWORD_SET", lane="original", subjects=_LANGUAGES,
      aliases=("IDIOMS", "PHRASES", "मुहावरे", "लोकोक्तियाँ"),
      brief="An idiom; the student gives its meaning or uses it in a sentence of their own.",
      example="Use the idiom in a sentence of your own: 'a piece of cake'.",
      answer="Any sentence using it to mean 'very easy'"),
    _("HOMOPHONE", "Homophones / Confusables", "F15", "NEW", "ONE_WORD",
      "Choosing between confusable words.", 1, (3, 8), "SHORT_TEXT", "IDENTIFY",
      lane="original", subjects=_LANGUAGES, aliases=("HOMOPHONES", "CHOOSE THE CORRECT WORD"),
      brief="A sentence with two confusable words in brackets; the student chooses the right one.",
      example="Choose the correct word: The (weather / whether) was pleasant yesterday.",
      answer="weather"),
    _("PREFIX_SUFFIX", "Prefix & Suffix / Word Formation", "F16", "NEW", "ONE_WORD",
      "Word formation.", 1, (4, 10), "SHORT_TEXT", "CREATE",
      marking="KEYWORD_SET", lane="original", subjects=_LANGUAGES, aliases=("PREFIX", "SUFFIX", "WORD FORMATION"),
      brief="A root word and a direction (add a prefix or suffix); the answer lists valid formations.",
      example="Form a new word by adding a suffix: care → ________",
      answer="careful / careless / caring"),
    _("WORD_FORM_CHANGE", "Gender, Number, Tense Forms", "F17", "NEW", "ONE_WORD",
      "Word forms.", 1, (1, 5), "SHORT_TEXT", "RECALL",
      marks_range=(1, 3), lane="original", subjects=_LANGUAGES,
      aliases=("PLURAL", "PLURAL FORM", "GENDER", "CHANGE THE GENDER"),
      brief="A word and the form to write (plural, feminine, past tense).",
      example="Write the plural form: child",
      answer="children"),
    _("SPELLING", "Spelling", "F18", "NEW", "MCQ",
      "Correct spelling.", 1, (1, 6), "MCQ_4", "IDENTIFY",
      options=FOUR, lane="original", subjects=_LANGUAGES, aliases=("CORRECT SPELLING", "CIRCLE THE CORRECTLY SPELT WORD"),
      brief="Four spellings of one word as options; exactly one is correct.",
      example="Circle the correctly spelt word.\n(a) recieve  (b) receive  (c) receeve  (d) recive",
      answer="(b) receive"),
]
