"""Family G — mathematics. Shapes that do not map onto generic descriptive types.

Geometric construction is catalogued once, under Family E (E10), because the
student produces a drawing; `also_in` records that it is G15 too.
"""

from __future__ import annotations

from services.question_types.catalog._build import family_builder

_ = family_builder("MATHEMATICS")

_MATHS = ("mathematics",)
_STEPS = "The answer is a marking scheme that gives marks to steps, not only to the final answer."

ENTRIES = [
    _("NUMERICAL", "Numerical / Calculation", "G1", "LIVE", "NUMERICAL",
      "Calculation.", 3, (3, 10), "NUMERIC", "APPLY",
      marks_range=(2, 5), marking="SCHEME", aliases=("NUMERICAL", "CALCULATION", "NUMERICALS"),
      brief=f"A calculation problem with all the data needed. {_STEPS}",
      example="Find the compound interest on ₹12,000 at 10% per annum for 2 years, compounded annually.",
      answer="₹2,520 · formula 1, substitution 1, answer 1"),
    _("WORD_PROBLEM", "Word Problem", "G2", "NEW", "NUMERICAL",
      "Translating a situation into mathematics.", 2, (1, 10), "NUMERIC", "APPLY",
      marks_range=(2, 5), marking="SCHEME", aliases=("WORD PROBLEM", "STORY SUM"),
      brief=f"A short everyday situation whose difficulty is comprehension, not computation; one clear question at the end. {_STEPS}",
      example="A shopkeeper had 5 boxes of pencils with 24 pencils in each box. He sold 87 pencils. How many pencils are left with him?",
      answer="33"),
    _("PROOF_DERIVATION", "Proof / Derivation", "G3", "DB", "SHORT_ANSWER",
      "Deductive reasoning.", 3, (8, 10), "LONG_TEXT", "JUSTIFY",
      marks_range=(3, 5), marking="SCHEME", subjects=("mathematics", "science"),
      aliases=("PROVE THAT", "PROOF", "DERIVATION", "DERIVE"),
      brief="A statement to prove or a relation to derive. The answer is a marking scheme listing the steps and their marks.",
      example="Prove that the angles opposite to equal sides of an isosceles triangle are equal.",
      answer="Given/to prove/construction 1 · congruence 1 · conclusion 1"),
    _("SOLVE_EQUATION", "Solve the Equation", "G4", "NEW", "NUMERICAL",
      "Algebraic solution.", 2, (6, 10), "NUMERIC", "APPLY",
      marks_range=(2, 3), marking="SCHEME", subjects=_MATHS, aliases=("SOLVE FOR X", "SOLVE THE EQUATION"),
      brief=f"One equation (or a pair) to solve for the unknown. {_STEPS}",
      example="Solve for x: 3x + 7 = 2x + 15",
      answer="x = 8"),
    _("SIMPLIFY_EVALUATE", "Simplify / Evaluate", "G5", "NEW", "NUMERICAL",
      "Manipulating an expression.", 2, (3, 10), "NUMERIC", "APPLY",
      marks_range=(1, 3), marking="SCHEME", subjects=_MATHS, aliases=("SIMPLIFY", "EVALUATE"),
      brief="One expression to simplify or evaluate, written in LaTeX delimiters \\( … \\).",
      example="Simplify: \\((2^5 \\times 2^3) \\div 2^6\\)",
      answer="4"),
    _("MISSING_NUMBER", "Find the Missing Number", "G6", "NEW", "ONE_WORD",
      "Number sense.", 1, (1, 5), "NUMERIC", "SEQUENCE",
      subjects=_MATHS, aliases=("MISSING NUMBERS", "FILL IN THE MISSING NUMBERS"),
      brief="A number sequence, sum or grid with one or two numbers missing, shown as ____.",
      example="Fill in the missing numbers: 14, 18, ____, 26, ____, 34",
      answer="22, 30"),
    _("MENSURATION_APPLIED", "Mensuration — Applied", "G7", "NEW", "NUMERICAL",
      "Area, perimeter, volume in context.", 3, (5, 10), "NUMERIC", "APPLY",
      marks_range=(3, 5), marking="SCHEME", subjects=_MATHS, aliases=("MENSURATION",),
      brief=f"A real object with its dimensions stated in words (never 'the figure shows'), asking for an area, volume or capacity. {_STEPS}",
      example="A cylindrical water tank has a radius of 1.4 m and a height of 3 m. How many litres of water can it hold? (Use π = 22/7)",
      answer="18,480 litres"),
    _("STATISTICS_COMPUTE", "Statistics — Compute", "G8", "NEW", "NUMERICAL",
      "Mean, median, mode from data.", 3, (7, 10), "NUMERIC", "APPLY",
      marks_range=(3, 5), stimulus="TABLE", marking="SCHEME", subjects=_MATHS,
      aliases=("MEAN MEDIAN MODE", "STATISTICS"),
      brief=f"A frequency table printed in the question, and a statistic to compute from it. {_STEPS}",
      example="Find the mean of the following distribution.\n| Class interval | 0–10 | 10–20 | 20–30 | 30–40 |\n| Frequency | 5 | 8 | 12 | 5 |",
      answer="Mean = 20.3"),
    _("NUMBER_PATTERN", "Pattern / Number Series", "G9", "NEW", "ONE_WORD",
      "Pattern recognition.", 1, (1, 8), "NUMERIC", "SEQUENCE",
      marks_range=(1, 2), subjects=_MATHS, aliases=("NUMBER PATTERN", "NUMBER SERIES"),
      brief="A number pattern with the next one or two terms to find; the answer states the rule.",
      example="Find the next two terms: 3, 6, 12, 24, ____, ____",
      answer="48, 96 — each term doubles"),
    _("PROVE_IDENTITY", "Prove the Identity", "G10", "NEW", "SHORT_ANSWER",
      "Trigonometric or algebraic identity.", 3, (9, 10), "LONG_TEXT", "JUSTIFY",
      marking="SCHEME", subjects=_MATHS, aliases=("PROVE THE IDENTITY",),
      brief="An identity to prove, written in LaTeX delimiters. The answer shows the steps from one side to the other.",
      example="Prove that: \\((1 + \\tan^2\\theta)(1 - \\sin\\theta)(1 + \\sin\\theta) = 1\\)"),
    _("GRAPHICAL_SOLUTION", "Graphical Solution", "G11", "NEW", "DIAGRAM",
      "Solving by drawing graphs.", 3, (9, 10), "DRAW", "APPLY",
      marks_range=(3, 5), stimulus="GRAPH", marking="SCHEME", subjects=_MATHS,
      aliases=("SOLVE GRAPHICALLY",),
      brief="A pair of linear equations to solve graphically, with a blank coordinate grid supplied in `figure` for the student. The grid carries no plotted lines.",
      example="Solve graphically: x + y = 5, 2x − y = 4",
      answer="x = 3, y = 2 · tables 1, lines 1, solution 1"),
    _("VERIFY_CHECK", "Verify / Check", "G12", "NEW", "SHORT_ANSWER",
      "Checking a property with numbers.", 1, (3, 8), "SHORT_TEXT", "JUSTIFY",
      marks_range=(1, 2), marking="SCHEME", subjects=_MATHS, aliases=("VERIFY",),
      brief="A property and specific numbers to verify it with.",
      example="Verify that 0 is the additive identity for the numbers 7 and −3."),
    _("ESTIMATION_ROUNDING", "Estimation & Rounding", "G13", "NEW", "NUMERICAL",
      "Estimating by rounding.", 1, (3, 7), "NUMERIC", "APPLY",
      marks_range=(1, 2), subjects=_MATHS, aliases=("ESTIMATE", "ROUNDING OFF"),
      brief="A calculation to estimate after rounding to a stated place.",
      example="Estimate the product 48 × 31 by rounding each number to the nearest ten.",
      answer="50 × 30 = 1500"),
    _("CASE_STUDY_MATHS", "Maths Case Study", "G14", "NEW", "CASE_STUDY",
      "Mathematics applied to a real-life scenario.", 4, (8, 10), "NUMERIC", "APPLY",
      stimulus="SCENARIO", container="SUB_PARTS", marking="SCHEME", subjects=_MATHS,
      aliases=("MATHS CASE STUDY", "CASE BASED MATHS"),
      brief="A real-life scenario with its numbers, then sub-questions (i) 1 mark, (ii) 1 mark, (iii) 2 marks. Section E of the CBSE Class 10 paper.",
      example="A school is designing a rectangular garden 30 m long and 20 m wide. A 2 m wide path runs inside along the boundary.\n(i) What is the area of the whole garden? (1)\n(ii) What are the dimensions of the inner rectangle? (1)\n(iii) Find the area of the path. (2)",
      answer="(i) 600 m² (ii) 26 m × 16 m (iii) 184 m²"),
]
