"""Family H — practical, computer and skill."""

from __future__ import annotations

from services.question_types.catalog._build import FOUR, family_builder

_ = family_builder("PRACTICAL")

ENTRIES = [
    _("EXPERIMENT_BASED", "Experiment Based", "H1", "LIVE", "EXPERIMENTAL",
      "Procedure, apparatus and observation.", 3, (6, 10), "SHORT_TEXT", "APPLY",
      marks_range=(2, 5), marking="SCHEME", subjects=("science",),
      aliases=("EXPERIMENTAL", "EXPERIMENT", "EXPERIMENT BASED"),
      brief="Ask the student to describe an experiment: aim, apparatus, procedure and observation. Never refer to a pictured set-up.",
      example="Describe an experiment to show that carbon dioxide is released during respiration. State the apparatus used and the observation.",
      answer="Apparatus 1 · procedure 2 · observation 1 · conclusion 1"),
    _("EXPERIMENT_DESIGN", "Design an Experiment", "H2", "NEW", "SHORT_ANSWER",
      "Variable control and method design.", 3, (6, 10), "LONG_TEXT", "CREATE",
      marks_range=(3, 5), marking="SCHEME", subjects=("science",), aliases=("DESIGN AN EXPERIMENT",),
      brief="A question to investigate; the student designs a simple experiment, naming the control and the variable changed.",
      example="Design a simple experiment to find out whether sunlight is necessary for photosynthesis. State your control and the variable you would change.",
      answer="Destarched plant 1 · cover part of a leaf (variable) 1 · uncovered leaf as control, iodine test 1"),
    _("OBSERVATION_RUBRIC", "Observation Rubric", "H3", "DB", "SHORT_ANSWER",
      "Internal assessment.", 1, (1, 10), "SHORT_TEXT", "APPLY",
      marks_range=(1, 10), marking="RUBRIC", availability="internal",
      reason="Internal assessment, not a printed paper item."),
    _("PORTFOLIO_ARTEFACT", "Portfolio Artefact", "H4", "DB", "SHORT_ANSWER",
      "Project and assignment tracking.", 1, (1, 10), "LONG_TEXT", "CREATE",
      marks_range=(1, 10), marking="RUBRIC", availability="internal",
      reason="Project tracking, not a printed paper item."),
    _("CODE_OUTPUT", "Predict the Code Output", "H5", "DB", "SHORT_ANSWER",
      "Tracing a program.", 2, (6, 10), "SHORT_TEXT", "INTERPRET",
      marks_range=(1, 3), stimulus="CODE", aliases=("OUTPUT OF THE CODE", "PREDICT THE OUTPUT"),
      brief="A short program (Python unless stated) in a code block; the student writes its exact output.",
      example="What will be the output of the following Python code?\nx = 5\nfor i in range(3):\n    x = x + i\nprint(x)",
      answer="8"),
    _("ALGORITHM_DESIGN", "Algorithm Design", "H6", "DB", "SHORT_ANSWER",
      "Step-by-step problem solving.", 3, (5, 10), "LONG_TEXT", "CREATE",
      marks_range=(2, 4), marking="SCHEME", aliases=("WRITE AN ALGORITHM",),
      brief="A small problem; the student writes numbered algorithm steps.",
      example="Write an algorithm to find the largest of three numbers."),
    _("FLOWCHART_DRAW", "Draw a Flowchart", "H7", "NEW", "DIAGRAM",
      "Representing an algorithm with flowchart symbols.", 3, (5, 10), "DRAW", "CREATE",
      marks_range=(3, 4), marking="SCHEME", aliases=("DRAW A FLOWCHART",),
      brief="A small problem; the student draws a flowchart with standard symbols. Never refer to a printed figure.",
      example="Draw a flowchart to check whether a number is even or odd."),
    _("CODE_DEBUG", "Debug the Code", "H8", "NEW", "SHORT_ANSWER",
      "Finding and fixing errors in code.", 2, (7, 10), "SHORT_TEXT", "CORRECT",
      marks_range=(2, 3), stimulus="CODE", aliases=("DEBUG", "FIND THE ERRORS"),
      brief="A short program with a stated number of errors in a code block; the student identifies and corrects each.",
      example="The following code has two errors. Identify and correct them.\nfor i in range(5)\nprint(i)",
      answer="Missing colon after range(5); print(i) must be indented."),
    _("CODE_WRITE", "Write the Code", "H9", "NEW", "SHORT_ANSWER",
      "Writing a small program.", 3, (7, 10), "LONG_TEXT", "CREATE",
      marks_range=(3, 5), marking="SCHEME", aliases=("WRITE A PROGRAM",),
      brief="A small task; the student writes a program. The answer is a sample program plus a marking scheme.",
      example="Write a Python program to print the multiplication table of a number entered by the user."),
    _("TOOL_IDENTIFY", "Identify Tool / Shortcut", "H10", "NEW", "MCQ",
      "Software tools and shortcuts.", 1, (3, 8), "MCQ_4", "IDENTIFY",
      options=FOUR, aliases=("KEYBOARD SHORTCUT",),
      brief="A question about a software tool or keyboard shortcut, with four options.",
      example="Which keyboard shortcut is used to copy selected text?\n(a) Ctrl + X  (b) Ctrl + C  (c) Ctrl + V  (d) Ctrl + Z",
      answer="(b) Ctrl + C"),
    _("SAFETY_PROCEDURE", "Safety / Procedure", "H11", "NEW", "SHORT_ANSWER",
      "Safe practice.", 3, (4, 10), "SHORT_TEXT", "RECALL",
      marks_range=(1, 3), marking="KEYWORD_SET", aliases=("SAFETY PRECAUTIONS",),
      brief="Ask for N safety precautions or procedure steps for a stated setting; one mark each.",
      example="State three safety precautions to be followed while working in a science laboratory."),
    # Seeded by migration 0012 but not in Draft 1 of the catalogue.
    _("PRACTICAL_TASK", "Practical Task", "H+1", "DB", "SHORT_ANSWER",
      "Hands-on skill.", 1, (1, 10), "SHORT_TEXT", "APPLY",
      marks_range=(1, 10), marking="RUBRIC", availability="internal",
      reason="Internal assessment, not a printed paper item.", notes="Seeded by migration 0012."),
    _("PROJECT_WORK", "Project Work", "H+2", "DB", "LONG_ANSWER",
      "Extended project.", 5, (1, 10), "LONG_TEXT", "CREATE",
      marks_range=(1, 20), marking="RUBRIC", availability="internal",
      reason="Project work, not a printed paper item.", notes="Seeded by migration 0012."),
]
