# Generated by Django 5.0.6 on 2026-08-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organization_monthly_token_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="email_domains",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="organizationinvite",
            name="role",
            field=models.CharField(
                choices=[("org_admin", "Organization Admin"), ("teacher", "Teacher")],
                default="org_admin",
                max_length=20,
            ),
        ),
    ]
