"use client";

/**
 * What one member has generated, opened from their row in the members table.
 *
 * The table already reports a token count, which says how much someone used
 * but nothing about what they produced. This is the other half of that: the
 * titles, subjects and dates behind the number.
 *
 * Metadata only, by design — the endpoint does not return question text, so
 * an admin can see the shape of a colleague's work without reading the papers
 * themselves.
 */

import { useEffect, useState } from "react";
import { FileText, Loader2 } from "lucide-react";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { listMemberPapers, type MemberPaper } from "@/lib/organizations-client";

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString(undefined, {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

export function MemberPapersDialog({
  orgId,
  member,
  onClose,
}: {
  orgId: string;
  /** The member whose papers to show; null keeps the dialog closed. */
  member: { user_id: string; name: string; email: string } | null;
  onClose: () => void;
}) {
  const [papers, setPapers] = useState<MemberPaper[] | null>(null);
  const [bank, setBank] = useState<{ projects: number; questions: number } | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!member) return;
    // Cleared on every open so the previous member's papers never flash up
    // under this member's name while the new request is in flight.
    setPapers(null);
    setBank(null);
    setError(null);

    let cancelled = false;
    listMemberPapers(orgId, member.user_id)
      .then((res) => {
        if (cancelled) return;
        setPapers(res.papers);
        setBank(res.question_bank);
      })
      .catch((err: any) => {
        if (!cancelled) setError(err?.message || "Failed to load papers");
      });
    return () => {
      cancelled = true;
    };
  }, [orgId, member]);

  return (
    <Dialog open={member !== null} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>{member?.name || member?.email}</DialogTitle>
          <DialogDescription>
            {papers === null
              ? "Papers generated by this member."
              : papers.length === 1
                ? "1 paper generated."
                : `${papers.length} papers generated.`}
          </DialogDescription>
        </DialogHeader>

        {error ? (
          <p className="py-6 text-center text-sm text-destructive">{error}</p>
        ) : papers === null ? (
          <div className="flex justify-center py-10">
            <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
          </div>
        ) : papers.length === 0 ? (
          <div className="space-y-2 py-8 text-center text-sm text-muted-foreground">
            <p>This member hasn&apos;t saved any papers yet.</p>
            {/* A paper only becomes a row when it is saved. Someone can
                generate a great deal and save none of it, and "0 papers"
                alone makes that look like the screen is broken. */}
            {bank && bank.questions > 0 && (
              <p>
                They have {bank.questions.toLocaleString()} question
                {bank.questions === 1 ? "" : "s"} in their question bank across{" "}
                {bank.projects} project{bank.projects === 1 ? "" : "s"} — generated,
                but not saved as a paper.
              </p>
            )}
          </div>
        ) : (
          <div className="max-h-[55vh] space-y-2 overflow-y-auto">
            {papers.map((paper) => {
              // Subject / class / board are all optional on the model, so the
              // sub-line is assembled from whatever is actually set.
              const facts = [paper.subject, paper.grade_class, paper.board].filter(Boolean);
              return (
                <div
                  key={paper.id}
                  className="flex items-start justify-between gap-3 rounded-lg border border-border p-2.5"
                >
                  <div className="flex min-w-0 gap-2.5">
                    <FileText
                      className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground"
                      aria-hidden
                    />
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium text-foreground">
                        {paper.title}
                      </p>
                      <p className="truncate text-xs text-muted-foreground">
                        {[...facts, formatDate(paper.created_at)].join(" · ")}
                      </p>
                    </div>
                  </div>
                  {paper.set_count > 1 && (
                    <Badge variant="secondary" className="shrink-0">
                      {paper.set_count} sets
                    </Badge>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
